# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 549bb134be59aa8244041034363b57218addf66a295667be7837682319a36399bc76adc1692e87a5cbef0062be87302af61383065a02fcf8600e733a10ba5074

test:
  secret_key_base: b8ccf7acc09bc5e8071feb939c9ed5ff68d703b53e27c7730f39853245abc22dcbc5c27a0dbc73f66aaccc5cf7761f9168d61db6ac685f75660513a866ecada8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
